-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 20:07:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Item` (
  `ID` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Price` DOUBLE NULL,
  `Seller` VARCHAR(45) NULL,
  `Quantity` INT NULL,
  `Description` VARCHAR(200) NULL,
  `RecommendedItemID` INT NULL,
  `ModelNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Cart` (
  `ID` INT NOT NULL,
  `Quantity` INT NULL,
  `TotalPrice` DOUBLE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Customer` (
  `ID` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `EmailAddress` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CartID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Cart` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Payment` (
  `CardNumber` INT NOT NULL,
  `PaymentType` VARCHAR(45) NULL,
  `ExpirationDate` DATETIME NOT NULL,
  `CVC` INT NOT NULL,
  PRIMARY KEY (`CardNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipment`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Shipment` (
  `ShippingNumber` INT NOT NULL,
  `ServiceProvider` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NOT NULL,
  `ChargeAmount` INT NULL,
  PRIMARY KEY (`ShippingNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Review` (
  `ID` INT NOT NULL,
  `DetailedReview` VARCHAR(250) NULL,
  `Rating` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ItemID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Item` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CustomerID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Customer` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Admin` (
  `ID` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  `DateJoined` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Order` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CartID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Cart` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ShipmentID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Shipment` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cart_has_Item`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Cart_has_Item` (
  `Cart_ID` INT NOT NULL,
  `Item_ID` INT NOT NULL,
  PRIMARY KEY (`Cart_ID`, `Item_ID`),
  INDEX `fk_Cart_has_Item_Item1_idx` (`Item_ID` ASC) VISIBLE,
  INDEX `fk_Cart_has_Item_Cart1_idx` (`Cart_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_has_Item_Cart1`
    FOREIGN KEY (`Cart_ID`)
    REFERENCES `mydb`.`Cart` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_has_Item_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `mydb`.`Item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_Payment`
-- -----------------------------------------------------
CREATE TABLE `default_schema`.`Customer_has_Payment` (
  `Customer_ID` INT NOT NULL,
  `Payment_CardNumber` INT NOT NULL,
  PRIMARY KEY (`Customer_ID`, `Payment_CardNumber`),
  INDEX `fk_Customer_has_Payment_Payment1_idx` (`Payment_CardNumber` ASC) VISIBLE,
  INDEX `fk_Customer_has_Payment_Customer1_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Payment_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `mydb`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Payment_Payment1`
    FOREIGN KEY (`Payment_CardNumber`)
    REFERENCES `mydb`.`Payment` (`CardNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
